export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const BASKET_ROUTE = '/basket'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const DIVICE_ROUTE = '/device'